version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/sports-version
    ports:
      - '27081:80'
    container_name: wxcloud_sports-version
    labels:
      - wxPort=27082
      - hostPort=27081
      - wxcloud=sports-version
      - role=container
    environment:
      - MYSQL_USERNAME=
      - MYSQL_PASSWORD=
      - MYSQL_ADDRESS=
networks:
  default:
    external:
      name: wxcb0
